# Generated by Django 2.2.4 on 2020-02-25 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_in', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Temp in')),
                ('temp_out', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Temp out')),
                ('temp_water', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Temp water')),
                ('pressure', models.PositiveSmallIntegerField(verbose_name='Pressure')),
                ('humidity_in', models.PositiveSmallIntegerField(verbose_name='Humidity in')),
                ('humidity_out', models.PositiveSmallIntegerField(verbose_name='Humidity out')),
                ('voltage', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Voltage')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='Time')),
            ],
            options={
                'verbose_name': 'Weather',
                'verbose_name_plural': 'Weather',
            },
        ),
    ]
